### ISSUE TITLE
RESPONSE content-type - application/javascript

### ISSUE THREAD

**Issue by avoinea** [eea/eea.facetednavigation#101]
When you enable EEA Faceted Navigation Add-on on Plone 5 it gets installed and you're redirected to Plone site, but this page has RESPONSE.headers = application/json thus it looks like it's broken.

Could find why this is happening, but seems that this code from registry.xml has something to do with it:

```
    <value key="resources">
      <element>browser</element>
      <element>ajaxfileupload</element>
      <element>bbq</element>
      <element>jstree</element>
      <element>select2uislider</element>
      <element>tagcloud</element>
    </value>
```

https://github.com/collective/eea.facetednavigation/blob/master/eea/facetednavigation/profiles/plone5/registry.xml#L6

**Comment by davisagli** [comment]
Sounds similar to https://github.com/plone/Products.CMFPlone/issues/1436

**Comment by avoinea** [comment]
The main suspect here is https://github.com/collective/collective.js.jqueryui/blob/master/collective/js/jqueryui/resources.py

**Comment by avoinea** [comment]
This issue also appears when you enable Faceted Navigation and then click on "Faceted Navigation > Configure"

**Comment by pbauer** [comment]
Probably the same issue: https://github.com/collective/demo.plone.de/issues/13
I don't think that collective.js.jqueryui is responsible since it is not used on http://demo.plone.de

**Comment by pbauer** [comment]
It can be triggered by enabling and disabling the development-mode in `@@resourceregistry-controlpanel` and then reloading `configure_faceted.html`.

**Comment by david-batranu** [comment]
The problem is in [`Products.CMFPlone.resources.browser.cook.cookWhenChangingSettings`](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/resources/browser/cook.py#L25)
[`ConfigJsView`](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/resources/browser/configjs.py#L85) get's called and it's `Content-Type` header leaks onto the main request's response.

The following code in `cook.py` will fix the issue but I think the real fix needs to be done in `plone.subrequest` as it doesn't seem right for subrequest headers to end up on the main request.

```python
def keep_response_headers(headers):
    def _decorator(func):
        def _func(context, bundle=None):
            keep = {}
            response = getRequest().RESPONSE

            for header in headers:
                keep[header] = response.getHeader(header)

            result = func(context, bundle)

            for header, value in keep.items():
                response.setHeader(header, value)

            return result
        return _func
    return _decorator


@keep_response_headers(['Content-Type'])
def cookWhenChangingSettings(context, bundle=None):
...

```

**Comment by avoinea** [comment]
New issue added plone/Products.CMFPlone#1806

**Comment by albieback** [comment]
In the demo video (https://www.youtube.com/watch?v=q26w7U83kzM), I can see that there is still some wrongly displayed responses (when eea.facetednavigation is activated and when facetedsearch is enabled in the folder).

This is the expected behavior, that will get solved when plone/Products.CMFPlone#1806 is closed, right?

**Comment by avoinea** [comment]
@albieback indeed
