### ISSUE TITLE
Facetednavigation breaks Plone folder contents and MCE file upload. Uninstall does not fix problem. 

### ISSUE THREAD

**Issue by mjmare** [eea/eea.facetednavigation#129]
With eea.facetednavigation (FN) installed and plone in production mode the folder contents behaves erratically. If one keeps refreshing the page at some point the folder_contents are not shown. Keep refreshing and it wil show again at some point. 
In the MCE editor the upload widget is not shown. 

In the web inspector multiple errors are shown, see screenshot.  
![screen shot 2017-05-30 at 23 07 12](https://cloud.githubusercontent.com/assets/1711378/26605275/aed729d0-458d-11e7-9100-226d380e1426.png)

Note: running Resources in Development mode will circumvent the problem. 

Finally uninstalling FN fails to uninstall all its bundles and resources. Only manually removing all FN related bundles and resources restores normal folder_contents and file upload behaviour. 

FN 10.3
Plone 5.0.7 (5017)
CMF 2.2.10
Zope 2.13.26
Python 2.7.13 (default, May 11 2017, 21:39:56) [GCC 4.9.2]
PIL 3.4.2 (Pillow)

Problems observed in Safari and Chrome.

**Comment by holdenhao** [comment]
We had the same issue on Plone 5.0.8 and eea.factednavigation 10.8.  We had to remove and re-add jstree via the resource registry as mentioned in https://github.com/eea/eea.jquery/issues/7 .  This issue seems to have been resolved.  It is possible we had the issue even if we are now using the latest version because we started out with a lower version of eea.facetednavigation in our buildout.

**Comment by avoinea** [comment]
Looks like this is already fixed within eea.jquery package
