### ISSUE TITLE
widgets not displaying the title of an item correctly

### ISSUE THREAD

**Issue by Mychae1** [eea/eea.facetednavigation#242]
It seems that on version 16.0 the title of a selected item doesn't appear properly for widgets in which you can browse and select items. It says "[object Object] instead of showing the title of the selected item.
One concrete example is related items widget of a Document but it seems to behave like this for these widgets everywhere:
![widget_related_items](https://user-images.githubusercontent.com/104088325/208156263-a7adcf02-ded4-40b2-8bdb-d64ab270573d.PNG)

**Comment by laulaz** [comment]
I confirm this bug : on a fresh Plone 6, installing `eea.facetednavigation` breaks the related item widget.

**Comment by laulaz** [comment]
@avoinea do you have plans to fix this (or not) ?

**Comment by avoinea** [comment]
Contributions are always welcomed :smile:

**Comment by laulaz** [comment]
This is where the issue comes from : 
https://github.com/eea/eea.facetednavigation/blob/949682e83ecff3fc74bec6c40884d29309e2b771/resources/plugins.js#L3

If we remove it, the related items widget works fine.

I suppose we could drop `select2` dependency because it is shipped with Plone, but I don't know (yet) what should be changed in `eea.facetednavigation` JS files ...
For now, simply removing it breaks the multi-selection widget (at least).

**Comment by gotcha** [comment]
See this PR https://github.com/collective/eea.facetednavigation/pull/62

This solves the related items widget issue.
Faceted multi-select widget seems to work properly.

**Comment by Gomez** [comment]
Fixed: https://github.com/eea/eea.facetednavigation/commit/cfe0b8e31fe24b84071368643e98821c4357d337

And should work with v16.2
