### ISSUE TITLE
The FIELDSET element should only be used to group fields.

### ISSUE THREAD

**Issue by ivanteoh** [eea/eea.facetednavigation#92]
Recently one of our 4.x plone sites was audited for WCAG 2.0 AA. The report came back and mentioned that removing the FIELDSET element in faceted navigation. The same effect can be achieved by using a DIV element and a style sheet class. The FIELDSET element should only be used to group fields.

**Comment by djay** [comment]
They way we propose fixing this and some other accessibilty isues is as follows

- Have an option to group by column rather than portlet. This will put a fieldset around a whole left or right column when multiple portlets are used. 
- It will ensure that only one submit button is used per column. If in filter mode, it will say filter, not search.
- it will be a single configuration option. (somewhere?)

**Comment by avoinea** [comment]
The fieldset element is actually grouping fields, think about Text widget for example.

Also, for backward compatibility and in order not to break people's layout with such a major change we decided not to implement this.
